use core::{Order, OrderBook, Trade};
use std::collections::BTreeMap;
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{TRAINING_R0_ELF, TRAINING_R0_ID};
use risc0_zkvm::{ExecutorEnv, default_prover, serde::from_slice};
use risc0_zkvm::sha::{Sha256 as _, Impl as Sha256};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let order_book: OrderBook = OrderBook::new(BTreeMap::new(), BTreeMap::new());
    let new_orders = vec![
        // 10 bids (buy orders) — prices from 995 to 1004
        Order::new(1,  1004, 50,  true),
        Order::new(2,  1003, 80,  true),
        Order::new(3,  1002, 120, true),
        Order::new(4,  1001, 60,  true),
        Order::new(5,  1000, 100, true),
        Order::new(6,  999,  90,  true),
        Order::new(7,  998,  70,  true),
        Order::new(8,  997,  40,  true),
        Order::new(9,  996,  110, true),
        Order::new(10, 995,  30,  true),
        // 10 asks (sell orders) — prices from 998 to 1007
        Order::new(11, 998,  60,  false),
        Order::new(12, 999,  45,  false),
        Order::new(13, 1000, 100, false),
        Order::new(14, 1001, 75,  false),
        Order::new(15, 1002, 80,  false),
        Order::new(16, 1003, 55,  false),
        Order::new(17, 1004, 90,  false),
        Order::new(18, 1005, 35,  false),
        Order::new(19, 1006, 65,  false),
        Order::new(20, 1007, 50,  false),
    ];
    let mut std_out = Vec::new();
    // Serialize new orders as flat u32 array: [id, price, qty, is_bid] per order
    let order_slice: Vec<u32> = new_orders.iter().flat_map(|o| {
        [o.id, o.price, o.qty, o.is_bid as u32]
    }).collect();
    let num_words = order_slice.len() as u32;
    let env = ExecutorEnv::builder()
        .write(&order_book)
        .unwrap()
        .write(&num_words)
        .unwrap()
        .write_slice(&order_slice)
        .stdout(&mut std_out)
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover
        .prove(env, TRAINING_R0_ELF)
        .unwrap();
    println!("User cycles: {}", prove_info.stats.user_cycles);

    // extract the receipt.
    let receipt = prove_info.receipt;

    let digest_bytes: &Vec<u8> = &receipt.journal.bytes;
    println!("Book Hash: {:?}", digest_bytes);

    let (trades, book): (Vec<Trade>, OrderBook) = from_slice(&std_out).unwrap();
    println!("trades: {:?}", trades);
    println!("Book: {:?}", book);

    // Match returned book hash with returned hash.
    let book_bytes = bincode::serialize(&book).unwrap();
    let book_hash = Sha256::hash_bytes(&book_bytes);

    assert_eq!(digest_bytes, book_hash.as_bytes());
    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt
        .verify(TRAINING_R0_ID)
        .unwrap();
}
